/*
 * Bundle APIs
 * Bundle API service specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vf.uk.dal.utility.entity;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Data;

/**
 * Discount
 */
@Data
public class Discounts {

	@JsonProperty("productLineId")
	private String productLineId = null;

	@JsonProperty("action")
	private String action = null;

	@JsonProperty("skuId")
	private String skuId = null;

	@JsonProperty("tag")
	private String tag = null;

	@JsonProperty("label")
	private String label = null;

	@JsonProperty("tenure")
	private String tenure = null;

	@JsonProperty("duration")
	private String duration = null;

	@JsonProperty("confirmedRequired")
	private String confirmedRequired = null;

	@JsonProperty("merchandisingMedia")
	private List<MediaLink> merchandisingMedia = new ArrayList<MediaLink>();

	@JsonIgnore
	private DiscountPrice discountPrice = null;

}
