//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 10:51:22 AM IST 
//

package com.vf.uk.dal.device.client.entity.bundle;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Data;

/**
 * Path
 * @author manoj.bera
 *
 */
@Data
public class Path {

	@JsonProperty("promotionID")
	private String promotionID;

	@JsonProperty("promotionProductLine")
	private String promotionProductLine;

	@JsonProperty("commitmentStart")
	private String commitmentStart;

	@JsonProperty("duration")
	private String duration;

	@JsonProperty("penalty")
	private Float penalty;

	@JsonProperty("proratePlan")
	private String proratePlan;

}
