/*
 * Promotions API
 * Promotion API service operations
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vf.uk.dal.utility.entity;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * BundleAndHardwarePromotions
 */
public class BundleAndHardwarePromotions {
  private String bundleId = null;

  private String hardwareId = null;
  
  private List<CataloguepromotionqueriesForBundleAndHardwareEntertainmentPacks> entertainmentPacks = null;
  
  private List<CataloguepromotionqueriesForBundleAndHardwareDataAllowances> dataAllowances = null;
  
  private List<CataloguepromotionqueriesForBundleAndHardwarePlanCouplingPromotions> planCouplingPromotions = null;
  
  private List<CataloguepromotionqueriesForBundleAndHardwareSash> sashBannerForPlan = null;
  
  private List<CataloguepromotionqueriesForBundleAndHardwareSecureNet> secureNet = new ArrayList<>();
  
  private List<CataloguepromotionqueriesForHardwareSash> sashBannerForHardware = null;
  
  private List<CataloguepromotionqueriesForBundleAndHardwareExtras> freeExtras = null;
   
  private List<CataloguepromotionqueriesForBundleAndHardwareAccessory> freeAccessory = null;
  
  private List<CataloguepromotionqueriesForBundleAndHardwareExtras> freeExtrasForPlan = null;
  
  private List<CataloguepromotionqueriesForBundleAndHardwareAccessory> freeAccForPlan = null;
  
  private List<CataloguepromotionqueriesForBundleAndHardwareExtras> freeExtrasForHardware = null;
  
  private List<CataloguepromotionqueriesForBundleAndHardwareAccessory> freeAccForHardware = null;
  
  /**
   * 
   * @param bundleId
   * @return
   */
  public BundleAndHardwarePromotions bundleId(String bundleId) {
    this.bundleId = bundleId;
    return this;
  }

   /**
   * Bundle sku id added to the basket
   * @return bundleId
  **/
  public String getBundleId() {
    return bundleId;
  }
/**
 * 
 * @param bundleId
 */
  public void setBundleId(String bundleId) {
    this.bundleId = bundleId;
  }
/**
 * 
 * @param hardwareId
 * @return
 */
  public BundleAndHardwarePromotions hardwareId(String hardwareId) {
    this.hardwareId = hardwareId;
    return this;
  }

   /**
   * Bundle sku id added to the basket
   * @return hardwareId
  **/
  public String getHardwareId() {
    return hardwareId;
  }
/**
 * 
 * @param hardwareId
 */
  public void setHardwareId(String hardwareId) {
    this.hardwareId = hardwareId;
  }
/**
 * 
 * @param sashBannerForHardware
 * @return
 */
  public BundleAndHardwarePromotions sashBannerForHardware(List<CataloguepromotionqueriesForHardwareSash> sashBannerForHardware) {
    this.sashBannerForHardware = sashBannerForHardware;
    return this;
  }
/**
 * 
 * @param sashBannerForHardwareItem
 * @return
 */
  public BundleAndHardwarePromotions addSashBannerForHardwareItem(CataloguepromotionqueriesForHardwareSash sashBannerForHardwareItem) {
    if (this.sashBannerForHardware == null) {
      this.sashBannerForHardware = new ArrayList<>();
    }
    this.sashBannerForHardware.add(sashBannerForHardwareItem);
    return this;
  }

   /**
   * Get sashBannerForHardware
   * @return sashBannerForHardware
  **/
  public List<CataloguepromotionqueriesForHardwareSash> getSashBannerForHardware() {
    return sashBannerForHardware;
  }
/**
 * 
 * @param sashBannerForHardware
 */
  public void setSashBannerForHardware(List<CataloguepromotionqueriesForHardwareSash> sashBannerForHardware) {
    this.sashBannerForHardware = sashBannerForHardware;
  }
/**
 * 
 * @param freeExtras
 * @return
 */
  public BundleAndHardwarePromotions freeExtras(List<CataloguepromotionqueriesForBundleAndHardwareExtras> freeExtras) {
    this.freeExtras = freeExtras;
    return this;
  }
/**
 * 
 * @param freeExtrasItem
 * @return
 */
  public BundleAndHardwarePromotions addFreeExtrasItem(CataloguepromotionqueriesForBundleAndHardwareExtras freeExtrasItem) {
    if (this.freeExtras == null) {
      this.freeExtras = new ArrayList<>();
    }
    this.freeExtras.add(freeExtrasItem);
    return this;
  }

   /**
   * Get freeExtras
   * @return freeExtras
  **/
  public List<CataloguepromotionqueriesForBundleAndHardwareExtras> getFreeExtras() {
    return freeExtras;
  }
/**
 * 
 * @param freeExtras
 */
  public void setFreeExtras(List<CataloguepromotionqueriesForBundleAndHardwareExtras> freeExtras) {
    this.freeExtras = freeExtras;
  }
/**
 * 
 * @param freeAccessory
 * @return
 */
  public BundleAndHardwarePromotions freeAccessory(List<CataloguepromotionqueriesForBundleAndHardwareAccessory> freeAccessory) {
    this.freeAccessory = freeAccessory;
    return this;
  }
/**
 * 
 * @param freeAccessoryItem
 * @return
 */
  public BundleAndHardwarePromotions addFreeAccessoryItem(CataloguepromotionqueriesForBundleAndHardwareAccessory freeAccessoryItem) {
    if (this.freeAccessory == null) {
      this.freeAccessory = new ArrayList<>();
    }
    this.freeAccessory.add(freeAccessoryItem);
    return this;
  }

   /**
   * Get freeAccessory
   * @return freeAccessory
  **/
  public List<CataloguepromotionqueriesForBundleAndHardwareAccessory> getFreeAccessory() {
    return freeAccessory;
  }
/**
 * 
 * @param freeAccessory
 */
  public void setFreeAccessory(List<CataloguepromotionqueriesForBundleAndHardwareAccessory> freeAccessory) {
    this.freeAccessory = freeAccessory;
  }
/**
 * 
 * @param planCouplingPromotions
 * @return
 */
  public BundleAndHardwarePromotions planCouplingPromotions(List<CataloguepromotionqueriesForBundleAndHardwarePlanCouplingPromotions> planCouplingPromotions) {
    this.planCouplingPromotions = planCouplingPromotions;
    return this;
  }
/**
 * 
 * @param planCouplingPromotionsItem
 * @return
 */
  public BundleAndHardwarePromotions addPlanCouplingPromotionsItem(CataloguepromotionqueriesForBundleAndHardwarePlanCouplingPromotions planCouplingPromotionsItem) {
    if (this.planCouplingPromotions == null) {
      this.planCouplingPromotions = new ArrayList<>();
    }
    this.planCouplingPromotions.add(planCouplingPromotionsItem);
    return this;
  }

   /**
   * Get planCouplingPromotions
   * @return planCouplingPromotions
  **/
  public List<CataloguepromotionqueriesForBundleAndHardwarePlanCouplingPromotions> getPlanCouplingPromotions() {
    return planCouplingPromotions;
  }
/**
 * 
 * @param planCouplingPromotions
 */
  public void setPlanCouplingPromotions(List<CataloguepromotionqueriesForBundleAndHardwarePlanCouplingPromotions> planCouplingPromotions) {
    this.planCouplingPromotions = planCouplingPromotions;
  }
/**
 * 
 * @param dataAllowances
 * @return
 */
  public BundleAndHardwarePromotions dataAllowances(List<CataloguepromotionqueriesForBundleAndHardwareDataAllowances> dataAllowances) {
    this.dataAllowances = dataAllowances;
    return this;
  }
/**
 * 
 * @param dataAllowancesItem
 * @return
 */
  public BundleAndHardwarePromotions addDataAllowancesItem(CataloguepromotionqueriesForBundleAndHardwareDataAllowances dataAllowancesItem) {
    if (this.dataAllowances == null) {
      this.dataAllowances = new ArrayList<>();
    }
    this.dataAllowances.add(dataAllowancesItem);
    return this;
  }

   /**
   * Get dataAllowances
   * @return dataAllowances
  **/
  public List<CataloguepromotionqueriesForBundleAndHardwareDataAllowances> getDataAllowances() {
    return dataAllowances;
  }
/**
 * 
 * @param dataAllowances
 */
  public void setDataAllowances(List<CataloguepromotionqueriesForBundleAndHardwareDataAllowances> dataAllowances) {
    this.dataAllowances = dataAllowances;
  }
/**
 * 
 * @param entertainmentPacks
 * @return
 */
  public BundleAndHardwarePromotions entertainmentPacks(List<CataloguepromotionqueriesForBundleAndHardwareEntertainmentPacks> entertainmentPacks) {
    this.entertainmentPacks = entertainmentPacks;
    return this;
  }
/**
 * 
 * @param entertainmentPacksItem
 * @return
 */
  public BundleAndHardwarePromotions addEntertainmentPacksItem(CataloguepromotionqueriesForBundleAndHardwareEntertainmentPacks entertainmentPacksItem) {
    if (this.entertainmentPacks == null) {
      this.entertainmentPacks = new ArrayList<>();
    }
    this.entertainmentPacks.add(entertainmentPacksItem);
    return this;
  }

   /**
   * Get entertainmentPacks
   * @return entertainmentPacks
  **/
  public List<CataloguepromotionqueriesForBundleAndHardwareEntertainmentPacks> getEntertainmentPacks() {
    return entertainmentPacks;
  }
/**
 * 
 * @param entertainmentPacks
 */
  public void setEntertainmentPacks(List<CataloguepromotionqueriesForBundleAndHardwareEntertainmentPacks> entertainmentPacks) {
    this.entertainmentPacks = entertainmentPacks;
  }
/**
 * 
 * @param sashBannerForPlan
 * @return
 */
  public BundleAndHardwarePromotions sashBannerForPlan(List<CataloguepromotionqueriesForBundleAndHardwareSash> sashBannerForPlan) {
    this.sashBannerForPlan = sashBannerForPlan;
    return this;
  }
/**
 * 
 * @param sashBannerForPlanItem
 * @return
 */
  public BundleAndHardwarePromotions addSashBannerForPlanItem(CataloguepromotionqueriesForBundleAndHardwareSash sashBannerForPlanItem) {
    if (this.sashBannerForPlan == null) {
      this.sashBannerForPlan = new ArrayList<>();
    }
    this.sashBannerForPlan.add(sashBannerForPlanItem);
    return this;
  }

   /**
   * Get sashBannerForPlan
   * @return sashBannerForPlan
  **/
  public List<CataloguepromotionqueriesForBundleAndHardwareSash> getSashBannerForPlan() {
    return sashBannerForPlan;
  }
/**
 * 
 * @param sashBannerForPlan
 */
  public void setSashBannerForPlan(List<CataloguepromotionqueriesForBundleAndHardwareSash> sashBannerForPlan) {
    this.sashBannerForPlan = sashBannerForPlan;
  }

/**
 * 
 * @return
 */
  public List<CataloguepromotionqueriesForBundleAndHardwareSecureNet> getSecureNet() {
	return secureNet;
}
/**
 * 
 * @param secureNet
 */
public void setSecureNet(List<CataloguepromotionqueriesForBundleAndHardwareSecureNet> secureNet) {
	this.secureNet = secureNet;
}
/**
 * 
 * @return
 */
public List<CataloguepromotionqueriesForBundleAndHardwareExtras> getFreeExtrasForPlan() {
	return freeExtrasForPlan;
}
/**
 * 
 * @param freeExtrasForPlan
 */
public void setFreeExtrasForPlan(List<CataloguepromotionqueriesForBundleAndHardwareExtras> freeExtrasForPlan) {
	this.freeExtrasForPlan = freeExtrasForPlan;
}


/**
 * 
 * @return
 */
public List<CataloguepromotionqueriesForBundleAndHardwareAccessory> getFreeAccForPlan() {
	return freeAccForPlan;
}
/**
 * 
 * @param freeAccForPlan
 */
public void setFreeAccForPlan(List<CataloguepromotionqueriesForBundleAndHardwareAccessory> freeAccForPlan) {
	this.freeAccForPlan = freeAccForPlan;
}
/**
 * 
 * @return
 */
public List<CataloguepromotionqueriesForBundleAndHardwareExtras> getFreeExtrasForHardware() {
	return freeExtrasForHardware;
}
/**
 * 
 * @param freeExtrasForHardware
 */
public void setFreeExtrasForHardware(List<CataloguepromotionqueriesForBundleAndHardwareExtras> freeExtrasForHardware) {
	this.freeExtrasForHardware = freeExtrasForHardware;
}
/**
 * 
 * @return
 */
public List<CataloguepromotionqueriesForBundleAndHardwareAccessory> getFreeAccForHardware() {
	return freeAccForHardware;
}
/**
 * 
 * @param freeAccForHardware
 */
public void setFreeAccForHardware(List<CataloguepromotionqueriesForBundleAndHardwareAccessory> freeAccForHardware) {
	this.freeAccForHardware = freeAccForHardware;
}

@Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BundleAndHardwarePromotions bundleAndHardwarePromotions = (BundleAndHardwarePromotions) o;
    return Objects.equals(this.bundleId, bundleAndHardwarePromotions.bundleId) &&
        Objects.equals(this.hardwareId, bundleAndHardwarePromotions.hardwareId) &&
        Objects.equals(this.sashBannerForHardware, bundleAndHardwarePromotions.sashBannerForHardware) &&
        Objects.equals(this.freeExtras, bundleAndHardwarePromotions.freeExtras) &&
        Objects.equals(this.freeAccessory, bundleAndHardwarePromotions.freeAccessory) &&
        Objects.equals(this.planCouplingPromotions, bundleAndHardwarePromotions.planCouplingPromotions) &&
        Objects.equals(this.dataAllowances, bundleAndHardwarePromotions.dataAllowances) &&
        Objects.equals(this.entertainmentPacks, bundleAndHardwarePromotions.entertainmentPacks) &&
        Objects.equals(this.sashBannerForPlan, bundleAndHardwarePromotions.sashBannerForPlan);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bundleId, hardwareId, sashBannerForHardware, freeExtras, freeAccessory, planCouplingPromotions, dataAllowances, entertainmentPacks, sashBannerForPlan);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BundleAndHardwarePromotions {\n");
    
    sb.append("    bundleId: ").append(toIndentedString(bundleId)).append("\n");
    sb.append("    hardwareId: ").append(toIndentedString(hardwareId)).append("\n");
    sb.append("    sashBannerForHardware: ").append(toIndentedString(sashBannerForHardware)).append("\n");
    sb.append("    freeExtras: ").append(toIndentedString(freeExtras)).append("\n");
    sb.append("    freeAccessory: ").append(toIndentedString(freeAccessory)).append("\n");
    sb.append("    planCouplingPromotions: ").append(toIndentedString(planCouplingPromotions)).append("\n");
    sb.append("    dataAllowances: ").append(toIndentedString(dataAllowances)).append("\n");
    sb.append("    entertainmentPacks: ").append(toIndentedString(entertainmentPacks)).append("\n");
    sb.append("    sashBannerForPlan: ").append(toIndentedString(sashBannerForPlan)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

