/*
 * Promotions API
 * Promotion API service operations
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vf.uk.dal.utility.entity;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import lombok.Data;

/**
 * CataloguepromotionqueriesForBundleAndHardwareExtras.
 */
@Data
public class CataloguepromotionqueriesForBundleAndHardwareExtras {

	/** The tag. */
	private String tag = null;

	/** The label. */
	private String label = null;

	/** The type. */
	private String type = null;

	/** The priority. */
	private String priority = null;

	/** The plancouple id. */
	private String plancoupleId = null;

	/** The description. */
	private String description = null;

	/** The package type. */
	private List<String> packageType = new ArrayList<>();

	/** The foot notes. */
	private List<String> footNotes = new ArrayList<>();

	/** The promotion media. */
	private String promotionMedia = null;

}
