/*
 * Promotions API
 * Promotion API service operations
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vf.uk.dal.utility.entity;

import java.util.Objects;

/**
 * CataloguepromotionqueriesForHardwareSash
 */
public class CataloguepromotionqueriesForHardwareSash {
	private String tag = null;

	private String label = null;

	private String type = null;

	private String priority = null;


	private String description = null;
	
	private String promotionMedia = null;

	public CataloguepromotionqueriesForHardwareSash tag(String tag) {
		this.tag = tag;
		return this;
	}

	/**
	 * Unique tag name for the merchandising promotion
	 * 
	 * @return tag
	 **/
	public String getTag() {
		return tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public CataloguepromotionqueriesForHardwareSash label(String label) {
		this.label = label;
		return this;
	}

	/**
	 * Descriptive text for the merchandising promotion
	 * 
	 * @return label
	 **/
	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public CataloguepromotionqueriesForHardwareSash type(String type) {
		this.type = type;
		return this;
	}

	/**
	 * Merchandising promotion type
	 * 
	 * @return type
	 **/
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public CataloguepromotionqueriesForHardwareSash priority(String priority) {
		this.priority = priority;
		return this;
	}

	/**
	 * Priority for the merchandising promotion
	 * 
	 * @return priority
	 **/
	public String getPriority() {
		return priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	

	public CataloguepromotionqueriesForHardwareSash description(String description) {
		this.description = description;
		return this;
	}

	/**
	 * Description of the promotion
	 * 
	 * @return description
	 **/
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getPromotionMedia() {
		return promotionMedia;
	}

	public void setPromotionMedia(String promotionMedia) {
		this.promotionMedia = promotionMedia;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		CataloguepromotionqueriesForHardwareSash cataloguepromotionqueriesForHardwareSash = (CataloguepromotionqueriesForHardwareSash) o;
		return Objects.equals(this.tag, cataloguepromotionqueriesForHardwareSash.tag)
				&& Objects.equals(this.label, cataloguepromotionqueriesForHardwareSash.label)
				&& Objects.equals(this.type, cataloguepromotionqueriesForHardwareSash.type)
				&& Objects.equals(this.priority, cataloguepromotionqueriesForHardwareSash.priority)
				&& Objects.equals(this.description, cataloguepromotionqueriesForHardwareSash.description);
	}

	@Override
	public int hashCode() {
		return Objects.hash(tag, label, type, priority, description);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class CataloguepromotionqueriesForHardwareSash {\n");

		sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
		sb.append("    label: ").append(toIndentedString(label)).append("\n");
		sb.append("    type: ").append(toIndentedString(type)).append("\n");
		sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
		sb.append("    description: ").append(toIndentedString(description)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
