/*
 * Bundle APIs
 * Bundle API service specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vf.uk.dal.utility.entity;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.Data;

/**
 * Discount
 */
@Data
public class Discounts {

	private String productLineId = null;

	private String action = null;

	private String skuId = null;

	private String tag = null;

	private String label = null;

	private String tenure = null;

	private String duration = null;

	private String confirmedRequired = null;

	private List<MediaLink> merchandisingMedia = new ArrayList<MediaLink>();

	@JsonIgnore
	private DiscountPrice discountPrice = null;

	
}
