resources:
- repo: self
  clean: true

queue:
  name: linux-agents
  demands: maven

steps:
- task: SonarSource.sonarqube.15B84CA1-B62F-4A2A-A403-89B77A063157.SonarQubePrepare@4
  ## This task initiates the link to SonarQube. This is a required task.
  displayName: 'Prepare analysis on SonarQube'
  inputs:
    SonarQube: 'Dev - External'
    scannerMode: Other

- task: Maven@2
  ## This task initiates a maven Package and Unit Test on the service. This is a required task.
  displayName: 'Package POM'
  inputs:
    testRunTitle: '$(Build.DefinitionName)-unittest'
    codeCoverageToolOption: JaCoCo
    sonarQubeRunAnalysis: true

- task: SonarSource.sonarqube.291ed61f-1ee4-45d3-b1b0-bf822d9095ef.SonarQubePublish@4
  ## This task posts the SonarQube quality gate on the Build. This is not required as yet.
  displayName: 'Publish Quality Gate Result'

- bash: |
   get_status=$(curl -s -u ${USER}:${TOKEN} https://sonarqube.vision.vodafoneaws.co.uk/api/qualitygates/project_status?projectKey=com.vf.uk.dal:$(Build.DefinitionName)-svc)
   echo $get_status
   status=$(jq '.projectStatus.status' <<< "${get_status}")
   echo $status
   if [[ ${status} == '"ERROR"' ]]; then
   echo "Fail"
   echo "##vso[task.logissue type=warning;]SonarQube quality gate failure.";
   fi
  displayName: 'Build Breaker'

- task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@5
  displayName: 'Check build quality'
  inputs:
    checkWarnings: true
    warningFailOption: fixed
    warningTaskFilters: '/Build Breaker/i'

- task: CopyFiles@2
  ## This copies jar file to the correct location within the VSTS agent.  This is a required task.
  displayName: 'Copy Files to: $(Build.SourcesDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(Build.SourcesDirectory)'
    flattenFolders: true

- bash: |
   Version=$(ls | grep '^dal-[A-Za-z0-9].*.jar$' | sed 's/[^0-9.]*\([0-9.]*\)\.jar/\1/')
   echo "##vso[task.setvariable variable=Version]$Version" 
  displayName: 'Get Version from Jar'
  ## This task get the artifact version from the Jar produced by the Maven Package phase. This is a required task.

- task: AmazonWebServices.aws-vsts-tools.S3Download.S3Download@1
  ## This task downloads the VSTS agent to the VSTS agent. This is currently a required task.
  displayName: 'S3 Download: AppD Agent'
  inputs:
    awsCredentials: 'non-prod'
    regionName: 'eu-west-1'
    bucketName: 'digitalx-app-commons3bucket'
    sourceFolder: artifacts/appd
    globExpressions: appdagent.tar
    targetFolder: '$(Build.SourcesDirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  ## This task publishes the VSTS agent to VSTS for use in the release. This is a required task.
  displayName: 'Publish Artifact: $(Build.DefinitionName)'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/$(Build.DefinitionName)-svc-$(Version).jar'
    ArtifactName: '$(Build.DefinitionName)'

- task: PublishBuildArtifacts@1
  ## This task publishes the VSTS test report to the VSTS Build. This is not a required task.
  displayName: 'Publish Artifact: test_results'
  inputs:
    PathtoPublish: 'target/surefire-reports'
    ArtifactName: 'test_results'

- task: PublishBuildArtifacts@1
  ## This task publishes the VSTS infrastructiure documents for use later in the build and release. This is a required task.
  displayName: 'Publish Artifact: infrastructure'
  inputs:
    PathtoPublish: infrastructure
    ArtifactName: infrastructure

- task: AmazonWebServices.aws-vsts-tools.CloudFormationCreateOrUpdateStack.CloudFormationCreateOrUpdateStack@1
  ## This task creates or updates the ECR that will be used to share the image accross accounts. This is a required task.
  displayName: 'Create/Update Stack: $(Build.DefinitionName)'
  inputs:
    awsCredentials: 'newvo-e'
    regionName: 'eu-west-1'
    stackName: '$(Build.DefinitionName)'
    templateFile: 'infrastructure/cf-ecrtemplate.yaml'
    templateParametersSource: inline
    templateParameters: |
     - ParameterKey: EcrName
       ParameterValue: "$(Build.DefinitionName)"
    warnWhenNoWorkNeeded: false
    timeoutInMins: 5

- task: Docker@0
  ## This task builds a docker image. This is a required task.
  displayName: 'Build an image'
  inputs:
    containerregistrytype: 'Container Registry'
    buildArguments: |
     MSNAME=$(Build.DefinitionName)
     VERSION=$(Version)
    imageName: '$(Build.DefinitionName):$(Build.BuildId)'
    includeLatestTag: true
    workingDirectory: '$(Build.ArtifactStagingDirectory)'

- task: AmazonWebServices.aws-vsts-tools.ECRPushImage.ECRPushImage@1
  ## This task pushes the image to the ECR and will tag the image with the Build ID. This is a required task.
  displayName: 'Push Image'
  inputs:
    awsCredentials: 'newvo-e'
    regionName: 'eu-west-1'
    sourceImageName: '$(Build.DefinitionName)'
    sourceImageTag: '$(Build.BuildId)'
    repositoryName: '$(Build.DefinitionName)'
    pushTag: '$(Build.BuildId)'
    autoCreateRepository: true

- task: AmazonWebServices.aws-vsts-tools.ECRPushImage.ECRPushImage@1
  ## This will tag the image with the code version. This is a required task.
  displayName: 'Tag Image: Version'
  inputs:
    awsCredentials: 'newvo-e'
    regionName: 'eu-west-1'
    sourceImageName: '$(Build.DefinitionName)'
    sourceImageTag: '$(Build.BuildId)'
    repositoryName: '$(Build.DefinitionName)'
    pushTag: '$(Version)'
    autoCreateRepository: true

- task: AmazonWebServices.aws-vsts-tools.ECRPushImage.ECRPushImage@1
  ## This will tag the image as latest. Currently this is not used however is still recommended.
  displayName: 'Tag Image: Latest'
  inputs:
    awsCredentials: 'newvo-e'
    regionName: 'eu-west-1'
    sourceImageName: '$(Build.DefinitionName)'
    sourceImageTag: '$(Build.BuildId)'
    repositoryName: '$(Build.DefinitionName)'
    autoCreateRepository: true
