//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 03:25:52 PM IST 
//


package com.vf.uk.dal.device.datamodel.bundle;

/*import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
*/ 

public class BundleDeviceSpecificPricingOverrides {

    private BundlePriceOverride bundlePriceOverride;

	
	public BundleDeviceSpecificPricingOverrides() {
		super();
		// TODO Auto-generated constructor stub
	}

	public BundlePriceOverride getBundlePriceOverride() {
		return bundlePriceOverride;
	}

	public void setBundlePriceOverride(BundlePriceOverride bundlePriceOverride) {
		this.bundlePriceOverride = bundlePriceOverride;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((bundlePriceOverride == null) ? 0 : bundlePriceOverride.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		BundleDeviceSpecificPricingOverrides other = (BundleDeviceSpecificPricingOverrides) obj;
		if (bundlePriceOverride == null) {
			if (other.bundlePriceOverride != null)
				return false;
		} else if (!bundlePriceOverride.equals(other.bundlePriceOverride))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "BundleDeviceSpecificPricingOverrides [bundlePriceOverride=" + bundlePriceOverride + "]";
	}

    

}
