//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 10:51:22 AM IST 
//


package com.vf.uk.dal.device.datamodel.bundle;


public class Commitment {

    private String period;
	
    private Boolean penalty;
	
	
	public Commitment() {
		super();
		// TODO Auto-generated constructor stub
	}
	public String getPeriod() {
		return period;
	}
	public void setPeriod(String period) {
		this.period = period;
	}
	public Boolean getPenalty() {
		return penalty;
	}
	public void setPenalty(Boolean penalty) {
		this.penalty = penalty;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((penalty == null) ? 0 : penalty.hashCode());
		result = prime * result + ((period == null) ? 0 : period.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Commitment other = (Commitment) obj;
		if (penalty == null) {
			if (other.penalty != null)
				return false;
		} else if (!penalty.equals(other.penalty))
			return false;
		if (period == null) {
			if (other.period != null)
				return false;
		} else if (!period.equals(other.period))
			return false;
		return true;
	}
	@Override
	public String toString() {
		return "Commitment [period=" + period + ", penalty=" + penalty + "]";
	}

	

}
