//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 10:51:22 AM IST 
//

package com.vf.uk.dal.device.datamodel.bundle;

import lombok.Data;

@Data
public class Commitment {

	private String period;

	private Boolean penalty;

	public Commitment() {
		super();
		// TODO Auto-generated constructor stub
	}
}
