//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 03:25:52 PM IST 
//

package com.vf.uk.dal.device.datamodel.bundle;

import java.util.List;

public class Misc {

	private List<ItemAttribute> itemAttribute;

	public Misc() {
		super();
		// TODO Auto-generated constructor stub
	}

	public List<ItemAttribute> getItemAttribute() {
		return itemAttribute;
	}

	public void setItemAttribute(List<ItemAttribute> itemAttribute) {
		this.itemAttribute = itemAttribute;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((itemAttribute == null) ? 0 : itemAttribute.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Misc other = (Misc) obj;
		if (itemAttribute == null) {
			if (other.itemAttribute != null)
				return false;
		} else if (!itemAttribute.equals(other.itemAttribute))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Misc [itemAttribute=" + itemAttribute + "]";
	}

}
