//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 03:25:52 PM IST 
//


package com.vf.uk.dal.device.datamodel.bundle;

import java.util.ArrayList;
import java.util.List;


public class PromoteAs { 
	
  
    private List<String> promotionName;

	
	public PromoteAs() {
		super();
		// TODO Auto-generated constructor stub
	}

	public List<String> getPromotionName() {
		return promotionName;
	}

	public void setPromotionName(List<String> promotionName) {
		this.promotionName = promotionName;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((promotionName == null) ? 0 : promotionName.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PromoteAs other = (PromoteAs) obj;
		if (promotionName == null) {
			if (other.promotionName != null)
				return false;
		} else if (!promotionName.equals(other.promotionName))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "PromoteAs [promotionName=" + promotionName + "]";
	}

	
    
    
}
