//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 10:51:22 AM IST 
//

package com.vf.uk.dal.device.datamodel.bundle;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Data;

/**
 * ServiceProduct
 * @author manoj.bera
 *
 */
@Data
public class ServiceProduct {

	@JsonProperty("id")
	private String id;

	@JsonProperty("bundled")
	private Boolean bundled;

	@JsonProperty("lineRentals")
	private List<LineRental> lineRentals;
}
