//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 10:51:22 AM IST 
//


package com.vf.uk.dal.device.datamodel.bundle;


public class TerminationFee {
  
    private Float charge;
	 
    private String proratePlan;

	 
   
    public TerminationFee() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Float getCharge() {
        return charge;
    }

    public void setCharge(Float value) {
        this.charge = value;
    }

    public String getProratePlan() {
        return proratePlan;
    }

    public void setProratePlan(String value) {
        this.proratePlan = value;
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((charge == null) ? 0 : charge.hashCode());
		result = prime * result + ((proratePlan == null) ? 0 : proratePlan.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TerminationFee other = (TerminationFee) obj;
		if (charge == null) {
			if (other.charge != null)
				return false;
		} else if (!charge.equals(other.charge))
			return false;
		if (proratePlan == null) {
			if (other.proratePlan != null)
				return false;
		} else if (!proratePlan.equals(other.proratePlan))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "TerminationFee [charge=" + charge + ", proratePlan=" + proratePlan + "]";
	}

}
