/*
 * Pricing APIs
 * Bundle API service operations
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vf.uk.dal.device.entity;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * MerchandisingPromotion
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-01-02T12:25:09.565Z")

public class MerchandisingPromotion   {
  @JsonProperty("tag")
  private String tag = null;

  @JsonProperty("label")
  private String label = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("discountId")
  private String discountId = null;

  @JsonProperty("mpType")
  private String mpType = null;

  @JsonProperty("priceEstablishedLabel")
  private String priceEstablishedLabel = null;

  @JsonProperty("priority")
  private Integer priority = null;

  public MerchandisingPromotion tag(String tag) {
    this.tag = tag;
    return this;
  }

   /**
   * Tag value of the merchandising promotion
   * @return tag
  **/
  @ApiModelProperty(value = "Tag value of the merchandising promotion")


  public String getTag() {
    return tag;
  }

  public void setTag(String tag) {
    this.tag = tag;
  }

  public MerchandisingPromotion label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Label value of the merchandising promotion
   * @return label
  **/
  @ApiModelProperty(value = "Label value of the merchandising promotion")


  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public MerchandisingPromotion description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description Text from MEF
   * @return description
  **/
  @ApiModelProperty(value = "Description Text from MEF")


  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public MerchandisingPromotion discountId(String discountId) {
    this.discountId = discountId;
    return this;
  }

   /**
   * Discount skud Id, if applicable
   * @return discountId
  **/
  @ApiModelProperty(value = "Discount skud Id, if applicable")


  public String getDiscountId() {
    return discountId;
  }

  public void setDiscountId(String discountId) {
    this.discountId = discountId;
  }

  public MerchandisingPromotion mpType(String mpType) {
    this.mpType = mpType;
    return this;
  }

   /**
   * Promotion Type
   * @return mpType
  **/
  @ApiModelProperty(value = "Promotion Type")


  public String getMpType() {
    return mpType;
  }

  public void setMpType(String mpType) {
    this.mpType = mpType;
  }

  public MerchandisingPromotion priceEstablishedLabel(String priceEstablishedLabel) {
    this.priceEstablishedLabel = priceEstablishedLabel;
    return this;
  }

   /**
   * Price Established label available in MEF file
   * @return priceEstablishedLabel
  **/
  @ApiModelProperty(value = "Price Established label available in MEF file")


  public String getPriceEstablishedLabel() {
    return priceEstablishedLabel;
  }

  public void setPriceEstablishedLabel(String priceEstablishedLabel) {
    this.priceEstablishedLabel = priceEstablishedLabel;
  }

  public MerchandisingPromotion priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * The priority of Merchandising Promotion
   * @return priority
  **/
  @ApiModelProperty(value = "The priority of Merchandising Promotion")


  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchandisingPromotion merchandisingPromotion = (MerchandisingPromotion) o;
    return Objects.equals(this.tag, merchandisingPromotion.tag) &&
        Objects.equals(this.label, merchandisingPromotion.label) &&
        Objects.equals(this.description, merchandisingPromotion.description) &&
        Objects.equals(this.discountId, merchandisingPromotion.discountId) &&
        Objects.equals(this.mpType, merchandisingPromotion.mpType) &&
        Objects.equals(this.priceEstablishedLabel, merchandisingPromotion.priceEstablishedLabel) &&
        Objects.equals(this.priority, merchandisingPromotion.priority);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tag, label, description, discountId, mpType, priceEstablishedLabel, priority);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchandisingPromotion {\n");
    
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    discountId: ").append(toIndentedString(discountId)).append("\n");
    sb.append("    mpType: ").append(toIndentedString(mpType)).append("\n");
    sb.append("    priceEstablishedLabel: ").append(toIndentedString(priceEstablishedLabel)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

