//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 05:45:04 PM IST 
//

package com.vf.uk.dal.device.datamodel.product;

public class Delivery {

	private String classification;

	private String partner;

	private String soaDeliveryMethod;

	private boolean weekend;

	public Delivery() {
		super();
		// TODO Auto-generated constructor stub
	}

	public String getClassification() {
		return classification;
	}

	public void setClassification(String value) {
		this.classification = value;
	}

	public String getPartner() {
		return partner;
	}

	public void setPartner(String value) {
		this.partner = value;
	}

	public String getSoaDeliveryMethod() {
		return soaDeliveryMethod;
	}

	public void setSoaDeliveryMethod(String value) {
		this.soaDeliveryMethod = value;
	}

	public boolean isWeekend() {
		return weekend;
	}

	public void setWeekend(boolean value) {
		this.weekend = value;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((classification == null) ? 0 : classification.hashCode());
		result = prime * result + ((partner == null) ? 0 : partner.hashCode());
		result = prime * result + ((soaDeliveryMethod == null) ? 0 : soaDeliveryMethod.hashCode());
		result = prime * result + (weekend ? 1231 : 1237);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Delivery other = (Delivery) obj;
		if (classification == null) {
			if (other.classification != null)
				return false;
		} else if (!classification.equals(other.classification))
			return false;
		if (partner == null) {
			if (other.partner != null)
				return false;
		} else if (!partner.equals(other.partner))
			return false;
		if (soaDeliveryMethod == null) {
			if (other.soaDeliveryMethod != null)
				return false;
		} else if (!soaDeliveryMethod.equals(other.soaDeliveryMethod))
			return false;
		if (weekend != other.weekend)
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Delivery [classification=" + classification + ", partner=" + partner + ", soaDeliveryMethod="
				+ soaDeliveryMethod + ", weekend=" + weekend + "]";
	}

}
