//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 10:51:22 AM IST 
//

package com.vf.uk.dal.device.datamodel.product;

public class Duration {

	private String uom;

	private String starts;

	private String value;

	public Duration() {
		super();
		// TODO Auto-generated constructor stub
	}

	public String getUOM() {
		return uom;
	}

	public void setUOM(String value) {
		this.uom = value;
	}

	public String getStarts() {
		return starts;
	}

	public void setStarts(String value) {
		this.starts = value;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((starts == null) ? 0 : starts.hashCode());
		result = prime * result + ((uom == null) ? 0 : uom.hashCode());
		result = prime * result + ((value == null) ? 0 : value.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Duration other = (Duration) obj;
		if (starts == null) {
			if (other.starts != null)
				return false;
		} else if (!starts.equals(other.starts))
			return false;
		if (uom == null) {
			if (other.uom != null)
				return false;
		} else if (!uom.equals(other.uom))
			return false;
		if (value == null) {
			if (other.value != null)
				return false;
		} else if (!value.equals(other.value))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Duration [uom=" + uom + ", starts=" + starts + ", value=" + value + "]";
	}

}
