//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 03:25:52 PM IST 
//

package com.vf.uk.dal.device.datamodel.product;

import java.sql.Timestamp;

public class ProductControl {

	private boolean isDisplayableinLife;
	private boolean isSellableinLife;
	private boolean isDisplayableAcq;
	private boolean isSellableRet;
	private boolean isDisplayableRet;
	private boolean isSellableAcq;
	private boolean isDisplayableSavedBasket;

	private Long order;
	private boolean preOrderable;
	private Timestamp availableFrom;
	private boolean backOrderable;
	private boolean affiliateExport;
	private String compareWith;
	private String backOrderMessage;

	public ProductControl() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
	 * Gets the value of the isDisplayableinLife property.
	 * 
	 */
	public boolean isIsDisplayableinLife() {
		return isDisplayableinLife;
	}

	/**
	 * Sets the value of the isDisplayableinLife property.
	 * 
	 */
	public void setIsDisplayableinLife(boolean value) {
		this.isDisplayableinLife = value;
	}

	/**
	 * Gets the value of the isSellableinLife property.
	 * 
	 */
	public boolean isIsSellableinLife() {
		return isSellableinLife;
	}

	/**
	 * Sets the value of the isSellableinLife property.
	 * 
	 */
	public void setIsSellableinLife(boolean value) {
		this.isSellableinLife = value;
	}

	/**
	 * Gets the value of the isDisplayableAcq property.
	 * 
	 */
	public boolean isIsDisplayableAcq() {
		return isDisplayableAcq;
	}

	/**
	 * Sets the value of the isDisplayableAcq property.
	 * 
	 */
	public void setIsDisplayableAcq(boolean value) {
		this.isDisplayableAcq = value;
	}

	/**
	 * Gets the value of the isSellableRet property.
	 * 
	 */
	public boolean isIsSellableRet() {
		return isSellableRet;
	}

	/**
	 * Sets the value of the isSellableRet property.
	 * 
	 */
	public void setIsSellableRet(boolean value) {
		this.isSellableRet = value;
	}

	/**
	 * Gets the value of the isDisplayableRet property.
	 * 
	 */
	public boolean isIsDisplayableRet() {
		return isDisplayableRet;
	}

	/**
	 * Sets the value of the isDisplayableRet property.
	 * 
	 */
	public void setIsDisplayableRet(boolean value) {
		this.isDisplayableRet = value;
	}

	/**
	 * Gets the value of the isSellableAcq property.
	 * 
	 */
	public boolean isIsSellableAcq() {
		return isSellableAcq;
	}

	/**
	 * Sets the value of the isSellableAcq property.
	 * 
	 */
	public void setIsSellableAcq(boolean value) {
		this.isSellableAcq = value;
	}

	/**
	 * Gets the value of the isDisplayableSavedBasket property.
	 * 
	 */
	public boolean isIsDisplayableSavedBasket() {
		return isDisplayableSavedBasket;
	}

	/**
	 * Sets the value of the isDisplayableSavedBasket property.
	 * 
	 */
	public void setIsDisplayableSavedBasket(boolean value) {
		this.isDisplayableSavedBasket = value;
	}

	/**
	 * Gets the value of the order property.
	 * 
	 * @return possible object is {@link Long }
	 * 
	 */
	public Long getOrder() {
		return order;
	}

	/**
	 * Sets the value of the order property.
	 * 
	 * @param value
	 *            allowed object is {@link Long }
	 * 
	 */
	public void setOrder(Long value) {
		this.order = value;
	}

	/**
	 * Gets the value of the preOrderable property.
	 * 
	 */
	public boolean isPreOrderable() {
		return preOrderable;
	}

	/**
	 * Sets the value of the preOrderable property.
	 * 
	 */
	public void setPreOrderable(boolean value) {
		this.preOrderable = value;
	}

	public Timestamp getAvailableFrom() {
		return availableFrom;
	}

	public void setAvailableFrom(Timestamp availableFrom) {
		this.availableFrom = availableFrom;
	}

	/**
	 * Gets the value of the backOrderable property.
	 * 
	 */
	public boolean isBackOrderable() {
		return backOrderable;
	}

	/**
	 * Sets the value of the backOrderable property.
	 * 
	 */
	public void setBackOrderable(boolean value) {
		this.backOrderable = value;
	}

	/**
	 * Gets the value of the affiliateExport property.
	 * 
	 */
	public boolean isAffiliateExport() {
		return affiliateExport;
	}

	/**
	 * Sets the value of the affiliateExport property.
	 * 
	 */
	public void setAffiliateExport(boolean value) {
		this.affiliateExport = value;
	}

	/**
	 * Gets the value of the compareWith property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCompareWith() {
		return compareWith;
	}

	/**
	 * Sets the value of the compareWith property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCompareWith(String value) {
		this.compareWith = value;
	}

	/**
	 * Gets the value of the backOrderMessage property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBackOrderMessage() {
		return backOrderMessage;
	}

	/**
	 * Sets the value of the backOrderMessage property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBackOrderMessage(String value) {
		this.backOrderMessage = value;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (affiliateExport ? 1231 : 1237);
		result = prime * result + ((availableFrom == null) ? 0 : availableFrom.hashCode());
		result = prime * result + ((backOrderMessage == null) ? 0 : backOrderMessage.hashCode());
		result = prime * result + (backOrderable ? 1231 : 1237);
		result = prime * result + ((compareWith == null) ? 0 : compareWith.hashCode());
		result = prime * result + (isDisplayableAcq ? 1231 : 1237);
		result = prime * result + (isDisplayableRet ? 1231 : 1237);
		result = prime * result + (isDisplayableSavedBasket ? 1231 : 1237);
		result = prime * result + (isDisplayableinLife ? 1231 : 1237);
		result = prime * result + (isSellableAcq ? 1231 : 1237);
		result = prime * result + (isSellableRet ? 1231 : 1237);
		result = prime * result + (isSellableinLife ? 1231 : 1237);
		result = prime * result + ((order == null) ? 0 : order.hashCode());
		result = prime * result + (preOrderable ? 1231 : 1237);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ProductControl other = (ProductControl) obj;
		if (affiliateExport != other.affiliateExport)
			return false;
		if (availableFrom == null) {
			if (other.availableFrom != null)
				return false;
		} else if (!availableFrom.equals(other.availableFrom))
			return false;
		if (backOrderMessage == null) {
			if (other.backOrderMessage != null)
				return false;
		} else if (!backOrderMessage.equals(other.backOrderMessage))
			return false;
		if (backOrderable != other.backOrderable)
			return false;
		if (compareWith == null) {
			if (other.compareWith != null)
				return false;
		} else if (!compareWith.equals(other.compareWith))
			return false;
		if (isDisplayableAcq != other.isDisplayableAcq)
			return false;
		if (isDisplayableRet != other.isDisplayableRet)
			return false;
		if (isDisplayableSavedBasket != other.isDisplayableSavedBasket)
			return false;
		if (isDisplayableinLife != other.isDisplayableinLife)
			return false;
		if (isSellableAcq != other.isSellableAcq)
			return false;
		if (isSellableRet != other.isSellableRet)
			return false;
		if (isSellableinLife != other.isSellableinLife)
			return false;
		if (order == null) {
			if (other.order != null)
				return false;
		} else if (!order.equals(other.order))
			return false;
		if (preOrderable != other.preOrderable)
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ProductControl [isDisplayableinLife=" + isDisplayableinLife + ", isSellableinLife=" + isSellableinLife
				+ ", isDisplayableAcq=" + isDisplayableAcq + ", isSellableRet=" + isSellableRet + ", isDisplayableRet="
				+ isDisplayableRet + ", isSellableAcq=" + isSellableAcq + ", isDisplayableSavedBasket="
				+ isDisplayableSavedBasket + ", order=" + order + ", preOrderable=" + preOrderable + ", availableFrom="
				+ availableFrom + ", backOrderable=" + backOrderable + ", affiliateExport=" + affiliateExport
				+ ", compareWith=" + compareWith + ", backOrderMessage=" + backOrderMessage + "]";
	}

}
