//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 03:25:52 PM IST 
//

package com.vf.uk.dal.device.datamodel.product;

import java.util.List;

public class ProductGroups {

	private List<ProductGroup> productGroup;

	public List<ProductGroup> getProductGroup() {
		return productGroup;
	}

	public void setProductGroup(List<ProductGroup> productGroup) {
		this.productGroup = productGroup;
	}

	public ProductGroups() {
		super();
		// TODO Auto-generated constructor stub
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((productGroup == null) ? 0 : productGroup.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ProductGroups other = (ProductGroups) obj;
		if (productGroup == null) {
			if (other.productGroup != null)
				return false;
		} else if (!productGroup.equals(other.productGroup))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ProductGroups [productGroup=" + productGroup + "]";
	}

}
