//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 03:25:52 PM IST 
//

package com.vf.uk.dal.device.datamodel.product;

public class ProductPriceOverride {

	private float priceNet;

	private float priceGross;

	private float priceVAT;

	public ProductPriceOverride() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
	 * Gets the value of the priceNet property.
	 * 
	 */
	public float getPriceNet() {
		return priceNet;
	}

	/**
	 * Sets the value of the priceNet property.
	 * 
	 */
	public void setPriceNet(float value) {
		this.priceNet = value;
	}

	/**
	 * Gets the value of the priceGross property.
	 * 
	 */
	public float getPriceGross() {
		return priceGross;
	}

	/**
	 * Sets the value of the priceGross property.
	 * 
	 */
	public void setPriceGross(float value) {
		this.priceGross = value;
	}

	/**
	 * Gets the value of the priceVAT property.
	 * 
	 */
	public float getPriceVAT() {
		return priceVAT;
	}

	/**
	 * Sets the value of the priceVAT property.
	 * 
	 */
	public void setPriceVAT(float value) {
		this.priceVAT = value;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + Float.floatToIntBits(priceGross);
		result = prime * result + Float.floatToIntBits(priceNet);
		result = prime * result + Float.floatToIntBits(priceVAT);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ProductPriceOverride other = (ProductPriceOverride) obj;
		if (Float.floatToIntBits(priceGross) != Float.floatToIntBits(other.priceGross))
			return false;
		if (Float.floatToIntBits(priceNet) != Float.floatToIntBits(other.priceNet))
			return false;
		if (Float.floatToIntBits(priceVAT) != Float.floatToIntBits(other.priceVAT))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ProductPriceOverride [priceNet=" + priceNet + ", priceGross=" + priceGross + ", priceVAT=" + priceVAT
				+ "]";
	}

}
