spring:
  application:
    name: DEVICES-V1
info:
  build:
    version: @project.version@
    projectName: @project.artifactId@
server:
  contextPath: /devices/catalogue
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password
    trust-store: classpath:myTrustStore.jks
    trust-store-password: password  
endpoints:
  enabled: false
  health:
    enabled: true

management:
  health:
      solr:
        enabled: false
icp:
  env:
    kafka:
      host: kafka
      port: 9092
      logTopic: logs
 
  config:
    jdbcUrl: jdbc:oracle:thin:@100.66.65.222:1521:oradb
    jdbcUserName: daluser
    jdbcUserPwd: simple4u
    
  service:  
    defaultPageSize: 1000
    defaultPageNumber: 0  

elasticsearch:
  host: https://vpc-digitalx-dev-solr-es-hne32eyterqfesg3zzkpeg25q4.eu-west-1.es.amazonaws.com/  

  cache:
    jcache:
      config: classpath:ehcache.xml  
---

spring:
  profiles: local
  application:
    name: DEVICES-V1

server:
  contextPath: /devices/catalogue
  port: 2238
  ssl:
    trust-store: classpath:alblowerkeystore.jks
    trust-store-password: tib123 
icp:
  config:
    jdbcUrl: jdbc:oracle:thin:@100.66.65.222:1521:oradb
    jdbcUserName: daluser
    jdbcUserPwd: simple4u
  service:  
    defaultPageSize: 1000
    defaultPageNumber: 0  
  restclient:
    mock: 
      enabled: true
  
  env:
    enableLogStreaming: false
  security:
    enabled: true
   

