AWSTemplateFormatVersion: 2010-09-09
Description: ECR template for a microservice that will allow images to be shared between AWS accounts.
Parameters:
  EcrName:
    Description: Name of the repository to be passed in from VSTS build.
    Type: String

Resources:
  ECRRepo: 
    Type: "AWS::ECR::Repository"
    Properties: 
      RepositoryName: !Ref EcrName
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: Allow
            Principal: 
              AWS: 
                - "arn:aws:iam::587413880611:root" #non-prod
                - "arn:aws:iam::175616551101:root" #prod 
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"