- ParameterKey: Environment
  ParameterValue: "${RELEASE_ENVIRONMENTNAME}"
- ParameterKey: Version
  ParameterValue: "${VERSION}"
- ParameterKey: ContextPath
  ParameterValue: "${CONTEXTPATH}"
- ParameterKey: EcrLocation
  ParameterValue: "${ECRLOCATION}"
- ParameterKey: BuildName
  ParameterValue: "${BUILD_DEFINITIONNAME}"
- ParameterKey: BuildID
  ParameterValue: "${BUILD_BUILDID}"
- ParameterKey: Priority
  ParameterValue: "${PRIORITY}"
- ParameterKey: MaxCapacity
  ParameterValue: "${MAXCAPACITY}"
- ParameterKey: MinCapacity
  ParameterValue: "${MINCAPACITY}"
- ParameterKey: DesiredCount
  ParameterValue: "${DESIREDCOUNT}"
- ParameterKey: Cpu
  ParameterValue: "${CPU}"
- ParameterKey: Memory
  ParameterValue: "${MEMORY}"
- ParameterKey: MemoryReservation
  ParameterValue: "${MEMORYRESERVATION}"
- ParameterKey: HostName
  ParameterValue: "${HOSTNAME}"
- ParameterKey: AppDPort
  ParameterValue: "${APPDPORT}"
- ParameterKey: AppDKey
  ParameterValue: "${APPDKEY}"
- ParameterKey: AppDFlag
  ParameterValue: "${APPDFLAG}"
- ParameterKey: XMS
  ParameterValue: "${XMS}"
- ParameterKey: XMX
  ParameterValue: "${XMX}"
- ParameterKey: HealthyThresholdCount
  ParameterValue: "${HealthyThresholdCount}"
- ParameterKey: UnhealthyThresholdCount
  ParameterValue: "${UnhealthyThresholdCount}"
- ParameterKey: HealthCheckTimeoutSeconds
  ParameterValue: "${HealthCheckTimeoutSeconds}"
- ParameterKey: HealthCheckIntervalSeconds
  ParameterValue: "${HealthCheckIntervalSeconds}"
- ParameterKey: icpconfigjdbcUrl
  ParameterValue: "${ICPCONFIGJDBCURL}"
- ParameterKey: icpconfigjdbcUserName
  ParameterValue: "${ICPCONFIGJDBCUSERNAME}"
- ParameterKey: icpconfigjdbcUserPwd
  ParameterValue: "${ICPCONFIGJDBCUSERPWD}"
- ParameterKey: elasticsearchhost
  ParameterValue: "${ELASTICSEARCHHOST}"
- ParameterKey: cdndomainhost
  ParameterValue: "${CDNDOMAINHOST}"
- ParameterKey: bazaarvoice
  ParameterValue: "${BAZAARVOICE}"
- ParameterKey: dalpublicmetricsexportenabled
  ParameterValue: "${DALPUBLICMETRICSEXPORTENABLED}"
- ParameterKey: springmetricsexportenabled
  ParameterValue: "${SPRINGMETRICSEXPORTENABLED}"  
