package com.vf.uk.dal.device.entity.test;
import java.beans.IntrospectionException;

import org.junit.Test;

import com.vf.uk.dal.device.dao.impl.DeviceDaoImpl;
import com.vf.uk.dal.device.entity.Accessory;
import com.vf.uk.dal.device.entity.BundleAllowance;
import com.vf.uk.dal.device.entity.BundleAndHardwareTuple;
import com.vf.uk.dal.device.entity.BundleHeaderForDevice;
import com.vf.uk.dal.device.entity.BundlePrice;
import com.vf.uk.dal.device.entity.CacheDeviceTileResponse;
import com.vf.uk.dal.device.entity.DeviceDetails;
import com.vf.uk.dal.device.entity.DeviceList;
import com.vf.uk.dal.device.entity.DeviceSummary;
import com.vf.uk.dal.device.entity.DeviceTile;
import com.vf.uk.dal.device.entity.Discount;
import com.vf.uk.dal.device.entity.Duration;
import com.vf.uk.dal.device.entity.Equipment;
import com.vf.uk.dal.device.entity.HardwarePrice;
import com.vf.uk.dal.device.entity.Insurance;
import com.vf.uk.dal.device.entity.KeepDeviceChangePlanRequest;
import com.vf.uk.dal.device.entity.MediaLink;
import com.vf.uk.dal.device.entity.Member;
import com.vf.uk.dal.device.entity.MerchandisingControl;
import com.vf.uk.dal.device.entity.MerchandisingPromotion;
import com.vf.uk.dal.device.entity.MerchandisingPromotions;
import com.vf.uk.dal.device.entity.MetaData;
import com.vf.uk.dal.device.entity.OfferPacks;
import com.vf.uk.dal.device.entity.Price;
import com.vf.uk.dal.device.entity.PriceForBundle;
import com.vf.uk.dal.device.entity.PriceForBundleAndHardware;
import com.vf.uk.dal.device.entity.ProductAvailability;
import com.vf.uk.dal.device.entity.ProductGroup;
import com.vf.uk.dal.device.entity.ProductGroupForDeviceListing;
import com.vf.uk.dal.device.entity.RequestForBundleAndHardware;
import com.vf.uk.dal.device.entity.SourcePackageSummary;
import com.vf.uk.dal.device.entity.Specification;
import com.vf.uk.dal.device.entity.SpecificationGroup;
import com.vf.uk.dal.device.entity.StepPricingInfo;
import com.vf.uk.dal.device.test.BeanTest;
import com.vf.uk.dal.device.utils.CohAddressProvider;
import com.vf.uk.dal.device.utils.Constants;
import com.vf.uk.dal.device.utils.ExceptionMessages;
import com.vf.uk.dal.utility.entity.BundleAndHardwarePromotions;
import com.vf.uk.dal.utility.entity.BundleAndHardwareRequest;
import com.vf.uk.dal.utility.entity.BundleDeviceAndAccessoryList;
import com.vf.uk.dal.utility.entity.BundleDeviceAndProductsList;
import com.vf.uk.dal.utility.entity.CataloguepromotionqueriesForBundleAndHardwareAccessory;
import com.vf.uk.dal.utility.entity.CataloguepromotionqueriesForBundleAndHardwareDataAllowances;
import com.vf.uk.dal.utility.entity.CataloguepromotionqueriesForBundleAndHardwareEntertainmentPacks;
import com.vf.uk.dal.utility.entity.CataloguepromotionqueriesForBundleAndHardwareExtras;
import com.vf.uk.dal.utility.entity.CataloguepromotionqueriesForBundleAndHardwarePlanCouplingPromotions;
import com.vf.uk.dal.utility.entity.CataloguepromotionqueriesForBundleAndHardwareSash;
import com.vf.uk.dal.utility.entity.CataloguepromotionqueriesForBundleAndHardwareSecureNet;
import com.vf.uk.dal.utility.entity.CataloguepromotionqueriesForHardwareSash;
import com.vf.uk.dal.utility.entity.ExtraPrice;
import com.vf.uk.dal.utility.entity.PriceForExtra;
import com.vf.uk.dal.utility.entity.PriceForProduct;
import com.vf.uk.dal.utility.entity.StockInfo;

public class EntityTest
{
 	@Test
 	public void testDeviceEntity() throws NoSuchMethodException, IntrospectionException
 	{
 		BeanTest.test(Accessory.class);
 		BeanTest.test(BundleAllowance.class);
 		BeanTest.test(BundleAndHardwareTuple.class);
 		BeanTest.test(BundleHeaderForDevice.class);
 		BeanTest.test(BundlePrice.class);
 		BeanTest.test(DeviceDetails.class);
 		BeanTest.test(DeviceList.class);
 		BeanTest.test(DeviceSummary.class);
 		BeanTest.test(DeviceTile.class);
 		BeanTest.test(Discount.class);
 		BeanTest.test(Duration.class);
 		BeanTest.test(Equipment.class);
// 		BeanTest.test(Error.class);
 		BeanTest.test(HardwarePrice.class);
 		BeanTest.test(Insurance.class);
 		BeanTest.test(MediaLink.class);
 		BeanTest.test(Member.class);
 		BeanTest.test(MerchandisingControl.class);
 		BeanTest.test(MerchandisingPromotion.class);
 		BeanTest.test(MerchandisingPromotions.class);
 		BeanTest.test(MetaData.class);
 		BeanTest.test(OfferPacks.class);
 		BeanTest.test(Price.class);
 		BeanTest.test(PriceForBundle.class);
 		BeanTest.test(PriceForBundleAndHardware.class);
 		BeanTest.test(ProductAvailability.class);
 		BeanTest.test(ProductGroup.class);
 		BeanTest.test(Specification.class);
 		BeanTest.test(SpecificationGroup.class);
 		BeanTest.test(StepPricingInfo.class);
 		BeanTest.test(CohAddressProvider.class);
 		BeanTest.test(Constants.class);
 		BeanTest.test(DeviceDaoImpl.class);
 		BeanTest.test(StockInfo.class);
 		BeanTest.test(ProductGroupForDeviceListing.class);
 		BeanTest.test(CacheDeviceTileResponse.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.PriceForBundleAndHardware.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.BundleAllowance.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.Discount.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.MerchandisingPromotion.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.StepPricingInfo.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.BundlePrice.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.HardwarePrice.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.MediaLink.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.MonthlyCostSaver.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.StockInfo.class);
 		//BeanTest.test(com.vf.uk.dal.utility.entity.BundleDetailsForDevice.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.Price.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.DiscountPrice.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.Duration.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.Discounts.class);
 		BeanTest.test(com.vf.uk.dal.device.entity.FacetWithCount.class);
 		//BeanTest.test(com.vf.uk.dal.device.entity.FeatureRating.class);
 		//BeanTest.test(com.vf.uk.dal.device.entity.IndividualReview.class);
 		BeanTest.test(com.vf.uk.dal.device.entity.NewFacet.class);
 		//BeanTest.test(com.vf.uk.dal.device.entity.RatingCount.class);
 		//BeanTest.test(com.vf.uk.dal.device.entity.Review.class);
 		//BeanTest.test(com.vf.uk.dal.device.entity.ReviewStatistics.class);
 		//BeanTest.test(com.vf.uk.dal.utility.entity.BundleHeaderForDevice.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.BasketItem.class);
 		BeanTest.test(com.vf.uk.dal.device.entity.Error.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.InstalledProduct.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.Preferences.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.StatusInfo.class);
 		BeanTest.test(com.vf.uk.dal.device.entity.Make.class);
 		BeanTest.test(com.vf.uk.dal.device.entity.Facet.class);
 		BeanTest.test(com.vf.uk.dal.device.entity.Insurances.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.Reason.class);
 		BeanTest.test(com.vf.uk.dal.device.entity.FacetedDevice.class);
 		BeanTest.test(com.vf.uk.dal.device.entity.Device.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.RecommendedProduct.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.JourneyData.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.BundleDetailsForAppSrv.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.CoupleRelation.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.BundleHeader.class);
 		BeanTest.test(com.vf.uk.dal.device.entity.Attributes.class);
 		BeanTest.test(com.vf.uk.dal.device.utils.MediaConstants.class);
 		BeanTest.test(KeepDeviceChangePlanRequest.class);
 		BeanTest.test(com.vf.uk.dal.utility.solr.entity.BundlePrice.class);
 		BeanTest.test(com.vf.uk.dal.utility.solr.entity.DevicePreCalculatedData.class);
 		BeanTest.test(com.vf.uk.dal.utility.solr.entity.HardwarePrice.class);
 		BeanTest.test(com.vf.uk.dal.utility.solr.entity.Media.class);
 		BeanTest.test(com.vf.uk.dal.utility.solr.entity.MerchandisingControl.class);
 		BeanTest.test(com.vf.uk.dal.utility.solr.entity.MonthlyDiscountPrice.class);
 		BeanTest.test(com.vf.uk.dal.utility.solr.entity.MonthlyPrice.class);
 		BeanTest.test(com.vf.uk.dal.utility.solr.entity.OneOffDiscountPrice.class);
 		BeanTest.test(com.vf.uk.dal.utility.solr.entity.OneOffPrice.class);
 		BeanTest.test(com.vf.uk.dal.utility.solr.entity.PriceInfo.class);
 		BeanTest.test(BundleDeviceAndAccessoryList.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.PriceForAccessory.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.RecommendedProductListResponse.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.RecommendedProductListRequest.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.CurrentJourney.class);
 		BeanTest.test(com.vf.uk.dal.utility.entity.BundleDetails.class);
 		BeanTest.test(ExceptionMessages.class);
 		BeanTest.test(com.vf.uk.dal.device.entity.Device.class);
 		BeanTest.test(RequestForBundleAndHardware.class);
 		BeanTest.test(com.vf.uk.dal.utility.solr.entity.OfferAppliedPriceDetails.class);
 		BeanTest.test(com.vf.uk.dal.device.entity.Asset.class);
 		BeanTest.test(com.vf.uk.dal.device.entity.Subscription.class);
 		BeanTest.test(com.vf.uk.dal.device.utils.CommonUtility.class);
 		BeanTest.test(com.vf.uk.dal.device.svc.impl.DeviceRecommendationServiceImpl.class);
 		BeanTest.test(ExtraPrice.class);
 		BeanTest.test(BundleDeviceAndProductsList.class);
 		BeanTest.test(PriceForProduct.class);
 		BeanTest.test(PriceForExtra.class);
 		BeanTest.test(com.vf.uk.dal.device.entity.AccessoryTileGroup.class);
 		BeanTest.test(SourcePackageSummary.class);
 		
 		BeanTest.test(CataloguepromotionqueriesForBundleAndHardwareEntertainmentPacks.class);
 		BeanTest.test(CataloguepromotionqueriesForBundleAndHardwareDataAllowances.class);
 		BeanTest.test(CataloguepromotionqueriesForBundleAndHardwarePlanCouplingPromotions.class);
 		BeanTest.test(CataloguepromotionqueriesForBundleAndHardwareSash.class);
 		BeanTest.test(CataloguepromotionqueriesForBundleAndHardwareSecureNet.class);
 		BeanTest.test(CataloguepromotionqueriesForHardwareSash.class);
 		BeanTest.test(CataloguepromotionqueriesForBundleAndHardwareExtras.class);
 		BeanTest.test(CataloguepromotionqueriesForBundleAndHardwareAccessory.class);
 		BeanTest.test(BundleAndHardwarePromotions.class);
 		BeanTest.test(BundleAndHardwareRequest.class);
 	}
}
