//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.02 at 03:25:52 PM IST 
//


package com.vf.uk.dal.device.datamodel.merchandisingPromotion;
import java.util.List;



public class Condition {
		
	
    private String productPath;
	
	private String packageType;
	
	private List<ComplexCondition> complexConditions;

	
	
    public Condition() {
		super();
	}



	public String getProductPath() {
		return productPath;
	}



	public void setProductPath(String productPath) {
		this.productPath = productPath;
	}



	public String getPackageType() {
		return packageType;
	}



	public void setPackageType(String packageType) {
		this.packageType = packageType;
	}



	public List<ComplexCondition> getComplexConditions() {
		return complexConditions;
	}



	public void setComplexConditions(List<ComplexCondition> complexConditions) {
		this.complexConditions = complexConditions;
	}



	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((complexConditions == null) ? 0 : complexConditions.hashCode());
		result = prime * result + ((packageType == null) ? 0 : packageType.hashCode());
		result = prime * result + ((productPath == null) ? 0 : productPath.hashCode());
		return result;
	}



	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Condition other = (Condition) obj;
		if (complexConditions == null) {
			if (other.complexConditions != null)
				return false;
		} else if (!complexConditions.equals(other.complexConditions))
			return false;
		if (packageType == null) {
			if (other.packageType != null)
				return false;
		} else if (!packageType.equals(other.packageType))
			return false;
		if (productPath == null) {
			if (other.productPath != null)
				return false;
		} else if (!productPath.equals(other.productPath))
			return false;
		return true;
	}



	@Override
	public String toString() {
		return "Condition [productPath=" + productPath + ", packageType=" + packageType + ", complexConditions="
				+ complexConditions + "]";
	}

	
	
    
}
